### PR TITLE
Check if exists directory before bundling

### LINKED ISSUE #40: `w4 bundle` should create directory recursively if the directory not exists
Example:
(Note: `dist` currently does not exists)
```sh
$ w4 bundle build/cart.wasm --html dist/index.html
OK! Bundled dist/index.html.
```
It's better to check if `dist` exists (and create if it does not) than just attempting to write the file to the HTML file.

### PR DESCRIPTION
**Pull request by takaeri**
This PR _should_ fix #40. Let me know if it doesn't or have any bugs

### CODE REVIEW

**Comment by aduros** [comment]
Hi, thanks!

This is for `w4 bundle` right? The check looks good to me, it just needs to be moved to `cli/lib/bundle.js` instead of `cli/lib/new.js`.

```js
const destDir = path.dirname(outFile);
... your existsSync check here
```

**Comment by aduros** [comment]
By the way, you can test your changes by running `npm link -g` inside the cli directory. This will install a `w4` command that uses your local changes :smiley:

**Comment by takaeri** [comment]
Ah yes. My bad for the wrong file. I'll submit again tomorrow.

**Comment by takaeri** [comment]
Closing in favor of #45

**Pull request closed without merging**
