### PR TITLE
Avoid errors with an old cmake used on libretro CI

### PR DESCRIPTION
**Pull request by yamt**
Fixes https://github.com/aduros/wasm4/issues/768

### CODE REVIEW

**Comment by warmenhoven** [comment]
Unfortunately this doesn't seem to have fixed it:

https://git.libretro.com/libretro/wasm4/-/pipelines/305380

**Comment by warmenhoven** [comment]
Looks like it just needs a similar if() wrapper around the one on line 217.

**Comment by LibretroAdmin** [comment]
Can this be merged @aduros ? We need it for the buildbot

**Comment by aduros** [comment]
Thanks @yamt !

**Pull request merged**
