### PR TITLE
Framebuffer refactorings

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by eXponenta** [comment]
Fixing  a https://github.com/aduros/wasm4/issues/11 will be nice addition for this PR

**Comment by aduros** [comment]
Looking good to me, thanks for the needed cleanup!

I wonder about the inlining of `drawPoint`, is it possible to do it in a way that doesn't sacrifice readability too much?

**Comment by MaxGraey** [comment]
> is it possible to do it in a way that doesn't sacrifice readability too much?

Basic idea manually hoist all invariants from loop, not just inline. Basically browser should do this by itself but it's not always happening. I could just revert this inlines back

**Comment by aduros** [comment]
Ok, let's revert the inlining for readability for now. I'd like to do the C port, fix bugs (#11), and add missing functionality (#13) before we go too far with optimization.

**Comment by MaxGraey** [comment]
Done!

**Comment by aduros** [comment]
Thanks!

**Pull request merged**
