### PR TITLE
Replaced Tabs with DropDown Menu

### PR DESCRIPTION
**Pull request by christopher-kleine**
- Replaced all Tabs with DropDown Menus in Tutorial
- Added TODO to all missing languages
- Fixed Ordering of Rust/Go to Go/Nim/Odin/Rust
- Fixed a small mistake in Zig (Moving the Snake)
- Added Publish infos for Zig

### CODE REVIEW

**Comment by aduros** [comment]
It's looking great! :smile: 

Is the `// TODO` text supposed to be displayed on the page? Right now if you select Odin the content is empty, which seems like something is broken.

**Comment by christopher-kleine** [comment]
Yes, this is supposed to show up. If I don't use a placeholder, it's simply empty. This at least shows that the content will be added in the future instead of a blank slate.

**Comment by aduros** [comment]
Yeah, but it looks like the TODO is not actually displayed on the website. Maybe it's being interpreted as a JS comment by docusaurus?

**Comment by christopher-kleine** [comment]
No, that was my mistake. I simply forgot it the "simple" cases. I've updated this and also fixed some other occurrences.

**Comment by aduros** [comment]
Ok,  thanks!

**Pull request merged**
