### PR TITLE
add incomplete nelua docs

### PR DESCRIPTION
**Pull request by AKDev21**

### CODE REVIEW

**Comment by AKDev21** [comment]
looks like something is missing for "changing the language on website to nelua" to work.

i would love if you anyone can fix that because i don't have experience with working with node.js, javscript and Docusaurus.

Thanks :smiley_cat:

**Comment by aduros** [comment]
Thanks a lot for tackling this! :smile: 

I just added the Nelua option to the site, if you want to update this branch with the latest it should show up. Please also replace `nelua` with `lua` as the markdown code language so that we get syntax highlighting. We can add true Nelua syntax highlighting later but it's probably a larger task.

**Comment by aduros** [comment]
Also please add the Nelua sections in alphabetical order, so between `go` and `nim' :nerd_face:

**Comment by AKDev21** [comment]
Done :smile_cat:

**Pull request merged**
