### PR TITLE
LIBRETRO: Add Emscripten compilation

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by ZetaNumbers** [comment]
Emscripten runs on js glue code, no? How could we add this?

**Comment by phcoder** [comment]
> Emscripten runs on js glue code, no? How could we add this?

Libretro-emscripten scripts handle this already

**Comment by aduros** [comment]
Platforms all the way down!

**Comment by ZetaNumbers** [comment]
But does it use JS glue code?

**Pull request merged**
