### PR TITLE
Added My Game "Wasm4 Gameboy VGM Player"

### PR DESCRIPTION
**Pull request by Penncilk**
Followed the instructions on the website :D

### CODE REVIEW

**Comment by aduros** [comment]
Ohh, nice!

**Comment by Penncilk** [comment]
Thank you! ^^

**Comment by Penncilk** [comment]
I was looking on the website to show my - friends by sending them a link, but I can't seem to find it on there, does it take a while for the website to process it? Or am I just missing it?

**Comment by Penncilk** [comment]
Never mind, I found it, thank you again! ^^

**Pull request merged**
